image: php:latest

variables:
  MYSQL_DATABASE: 2note
  MYSQL_ROOT_PASSWORD: 123456
  MYSQL_USER: 2note
  MYSQL_PASSWORD: 123456

services:
  - memcached
  - redis
  - mysql

before_script:
  - sed -i "s@http://deb.debian.org@http://mirrors.aliyun.com@g" /etc/apt/sources.list && sed -i "s@http://security.debian.org@http://mirrors.aliyun.com@g" /etc/apt/sources.list && rm -Rf /var/lib/apt/lists/* &&  cat /etc/apt/sources.list
  - apt-get update -y
  - apt-get install -y git libzip-dev libpng-dev libbz2-dev
  # Install PHP extensions
  - docker-php-source extract && docker-php-ext-install gd zip bz2
  - pecl install redis && docker-php-ext-enable redis
  # Install & enable Xdebug for code coverage reports
  - pecl install xdebug && docker-php-ext-enable xdebug
  # Install and run Composer
  - curl -sS https://mirrors.aliyun.com/composer/composer.phar >> composer.phar && php composer.phar config -g repo.packagist composer https://mirrors.aliyun.com/composer/ && php composer.phar install
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate:fresh

test:
  #script: vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never
  script: vendor/bin/phpunit --configuration phpunit.xml --colors=never